services:
  traefik:
    command:
      - --providers.docker
      - --providers.file.filename=/etc/traefik/dynamic.yml
    image: docker.io/traefik:v3.4.1
    ports:
      - "${EXTERNAL_PORT}:80"
      # Uncomment this line to enable the traefik dashboard
      # - "8080:8080"
      # Uncomment this line to enable HTTPS
      # - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

    networks:
      - traefik

  frontend:
    build: ./Frontend
    restart: always
    image: ghcr.io/uni-bremen-agst/see-manager-frontend:latest
    depends_on:
      - backend
      - traefik
    networks:
      - traefik
      - default

  backend:
    privileged: true
    build: ./Backend
    image: ghcr.io/uni-bremen-agst/see-manager-backend:latest
    restart: always
    depends_on:
      - traefik
    volumes:
      - backend-data:/see
      # Docker daemon must be reachable from backend container to spawn game servers.
      - ${DOCKER_SOCKET}:/var/run/docker.sock
    environment:
      # You should not change these values here.
      # Use the env file instead
      BACKEND_DOMAIN: ${DOMAIN_NAME}
      FRONTEND_DOMAIN: ${DOMAIN_NAME}
      FRONTEND_SCHEME: HTTP
      FILESTORAGE_DIR: /see/file-storage
      SQLITE_DB_FILE: /see/database.db
      # This is the docker host's external IP or domain. Game servers will be reachable on this host.
      DOCKER_EXTERNAL_HOST: ${DOCKER_EXTERNAL_HOST}
      GAME_SERVER_IMAGE: ${GAME_SERVER_IMAGE}
      # JWT settings
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      # This will add an admin account to the backend. Use with care!
      ADD_ADMIN_USERNAME: ${ADD_ADMIN_USERNAME}
      ADD_ADMIN_PASSWORD: ${ADD_ADMIN_PASSWORD}
    networks:
      - traefik
      - default

networks:
  traefik:
  default:

volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend-data
